# Custom dataset config for your data
dataset_name: "YOUR_DATASET" 
dataset_path: "/Users/vikaskumar/Downloads/FUnIE-GAN-master/FinalProject/data/"

# image info
chans: 3
im_width: 256
im_height: 256

# training params
val_interval: 500  # steps
ckpt_interval: 5   # epochs